### ISSUE TITLE
unable to provide input to the ssolver

### ISSUE THREAD

**Issue by ksrikar1234** [Sirsireesh/Sudoku-Solver#23]
Unable to provide input values to the program after building the ssolver application.
It opens nicely and asks to enter the values in the Sudoku. After giving a single input value ,it just closes. What may be the problem? I used GCC compiler to build it on a windows 7 OS platform. What is the syntax for giving input values?

**Comment by SirSireesh** [comment]
> What may be the problem?

Windows puts `\r\n` in the buffer when the "enter key" is pressed. This is as opposed to every modern rational OS which just puts `\n` in the buffer. Probably the reason. You can check by running the test suite. `./ssolver.exe <./test-sudokus/test.sudoku`

**Comment by ksrikar1234** [comment]
Fixed😊😊!!!! Works fine in command prompt.

**Comment by SirSireesh** [comment]
@ksrikar1234 you hvent released the changes made to the source code. This is a gross violation of the GPL v3 license under which Sudoku-Solver has been shared. I request you to publish the changes ASAP or I will be forced to take legal action.
