### ISSUE TITLE
Make it to run in termux

### ISSUE THREAD

**Issue by ksrikar1234** [Sirsireesh/Sudoku-Solver#24]
What should I do if I want to run it with   default g++ or clang-8 compilers in termux? I would like to run it in termux.
Edit: replacing c08 by clang-8.

**Comment by SirSireesh** [comment]
You can't. Besides there is no such thing as C08. There is C99, then C11 and finally C18.

The code relies heavily on `std::vector`, `std::list`, `foreach`, `std::string` and other C++11 features. You would have to rewrite those bits in C. I would instead suggest getting a C++14 compiler on termux. The default `clang` compiler should work.
