### ISSUE TITLE
Hidden Pair does not work

### ISSUE THREAD

**Issue by SirSireesh** [Sirsireesh/Sudoku-Solver#3]
The hidden pair function does not detect hidden pairs.
@dkiran100, Please rewrite the function, so that it detects hidden pairs
[Sudoku Wiki Link](http://www.sudokuwiki.org/Hidden_Candidates)

**Comment by chin123** [comment]
Hey, still waiting for this bugfix. It is affecting my production systems and I would really like it to be fixed, thank you!

**Comment by SirSireesh** [comment]
fixed in commit 1856fc553aa4bdb58c66e5f4cfd5e64f8b546f2a
